// ============================================================
// Audit Export – CSV and PDF generation
// Receives a prepared AuditLogDTO[] and streams the file.
// ============================================================

import type { Response } from 'express';
import type { AuditLogDTO } from '../types/audit.types.js';

// ---- CSV ----------------------------------------------------

export function exportAuditCsv(logs: AuditLogDTO[], res: Response): void {
  const escape = (v: unknown): string =>
    `"${String(v ?? '').replace(/"/g, '""').replace(/\n/g, ' ')}"`;

  const headers = [
    'Timestamp',
    'Action',
    'Entity Type',
    'Entity Name',
    'Entity ID',
    'Details',
    'Admin Name',
    'IP Address',
    'Status',
    'Remarks',
  ];

  const rows = logs.map((log) => [
    escape(new Date(log.timestamp).toLocaleString('en-US')),
    escape(log.action),
    escape(log.entityType),
    escape(log.entityName),
    escape(log.entityId),
    escape(log.details),
    escape(log.adminName),
    escape(log.ipAddress),
    escape(log.status),
    escape(log.remarks ?? ''),
  ]);

  const csv = [headers.map(escape), ...rows]
    .map((row) => row.join(','))
    .join('\n');

  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', 'attachment; filename="audit-log.csv"');
  res.send(csv);
}

// ---- PDF (pdfkit) -------------------------------------------

export async function exportAuditPdf(logs: AuditLogDTO[], res: Response): Promise<void> {
  const PDFDocument = (await import('pdfkit')).default;

  const NAVY  = '#0F2942';
  const GOLD  = '#D4AF37';
  const WHITE = '#FFFFFF';
  const SLATE = '#64748B';
  const SLATE_LIGHT = '#F8FAFC';
  const BORDER = '#E2E8F0';

  const doc = new PDFDocument({ size: 'A4', margin: 0, autoFirstPage: false });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="audit-log.pdf"');
  doc.pipe(res);

  const PAGE_W = 595.28;
  const PAGE_H = 841.89;
  const MARGIN = 36;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  const generatedAt = new Date();
  const dateStr = generatedAt.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = generatedAt.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });

  let pageNum = 0;

  const addPage = () => {
    doc.addPage({ size: 'A4', margin: 0 });
    pageNum++;

    // Header bar
    doc.rect(0, 0, PAGE_W, 32).fill(NAVY);
    doc.fillColor(GOLD).fontSize(9).font('Helvetica-Bold')
      .text('IUCB', MARGIN, 11, { continued: true })
      .fillColor(WHITE).font('Helvetica')
      .text('  |  Audit Log Export  |  CONFIDENTIAL');
    doc.fillColor(WHITE).fontSize(8)
      .text(`Page ${pageNum}  |  ${dateStr}`, MARGIN, 11, { align: 'right', width: CONTENT_W });

    // Footer bar
    doc.rect(0, PAGE_H - 24, PAGE_W, 24).fill(NAVY);
    doc.fillColor(WHITE).fontSize(7).font('Helvetica')
      .text(
        `Generated by IUCB Management System  •  ${dateStr} ${timeStr}  •  Page ${pageNum}`,
        MARGIN,
        PAGE_H - 16,
        { width: CONTENT_W, align: 'center' },
      );
  };

  // Table column definitions
  const cols = [
    { label: 'Timestamp',   width: 90  },
    { label: 'Action',      width: 68  },
    { label: 'Entity Type', width: 72  },
    { label: 'Entity Name', width: 120 },
    { label: 'Admin',       width: 80  },
    { label: 'Status',      width: 45  },
    { label: 'IP Address',  width: 44  },
  ];

  const drawTableHeader = (y: number): number => {
    doc.rect(MARGIN, y, CONTENT_W, 20).fill(NAVY);
    let x = MARGIN + 5;
    cols.forEach((col) => {
      doc.fillColor(WHITE).font('Helvetica-Bold').fontSize(7)
        .text(col.label, x, y + 6, { width: col.width - 5, lineBreak: false });
      x += col.width;
    });
    return y + 20;
  };

  const checkBreak = (y: number, needed: number): number => {
    if (y + needed > PAGE_H - 40) {
      addPage();
      return 40;
    }
    return y;
  };

  addPage();
  let y = 44;

  // Title block
  doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(14)
    .text('Audit Log Report', MARGIN, y, { width: CONTENT_W });
  y += 20;
  doc.fillColor(SLATE).font('Helvetica').fontSize(9)
    .text(
      `Generated on ${dateStr} at ${timeStr}  |  Total records: ${logs.length}`,
      MARGIN, y, { width: CONTENT_W },
    );
  y += 20;

  // Divider
  doc.rect(MARGIN, y, CONTENT_W, 1).fill(GOLD);
  y += 10;

  // Table
  y = drawTableHeader(y);

  if (logs.length === 0) {
    doc.rect(MARGIN, y, CONTENT_W, 24).fill(SLATE_LIGHT);
    doc.fillColor(SLATE).font('Helvetica').fontSize(8)
      .text('No audit records found.', MARGIN + 8, y + 8, { width: CONTENT_W - 16, align: 'center' });
    y += 24;
  } else {
    logs.forEach((log, idx) => {
      const ROW_H = 20;
      y = checkBreak(y, ROW_H + 2);
      if (y === 40) {
        y = drawTableHeader(y);
      }

      const bg = idx % 2 === 0 ? WHITE : SLATE_LIGHT;
      doc.rect(MARGIN, y, CONTENT_W, ROW_H).fill(bg);
      doc.rect(MARGIN, y + ROW_H - 1, CONTENT_W, 1).fill(BORDER);

      const ts = new Date(log.timestamp).toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        year: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
      });

      const cells = [
        ts,
        log.action,
        log.entityType,
        log.entityName.length > 20 ? log.entityName.substring(0, 18) + '…' : log.entityName,
        log.adminName,
        log.status,
        log.ipAddress,
      ];

      let x = MARGIN + 5;
      cells.forEach((cell, ci) => {
        doc.fillColor(NAVY).font('Helvetica').fontSize(7)
          .text(String(cell), x, y + 6, { width: cols[ci].width - 5, lineBreak: false });
        x += cols[ci].width;
      });

      y += ROW_H;
    });
  }

  doc.end();
}
