import { z } from "zod";

export const issueCredentialSchema = z.object({
  // credentialNumber is now auto-generated by the backend, not accepted as input
  applicationId: z.string().uuid("Invalid Application ID"),
  standard: z.string().min(2, "ISO standard is required"),
  issueDate: z.coerce.date(),
  expiryDate: z.coerce.date(),
  status: z.enum(["VALID", "REVOKED", "EXPIRED"]).optional().default("VALID"),
  auditorId: z.string().uuid("Invalid Auditor ID").optional(),
  internalNotes: z.string().optional(),
});

export const revokeCredentialSchema = z.object({
  reason: z.string().min(5, "Revocation reason required").optional(),
});

export const credentialQuerySchema = z.object({
  page: z.coerce.number().int().min(1).optional().default(1),
  limit: z.coerce.number().int().min(1).max(500).optional().default(20),
  status: z.enum(["VALID", "REVOKED", "EXPIRED"]).optional(),
  organizationId: z.string().uuid().optional(),
  search: z.string().optional(),
});
