/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyTrainingInstituteRouteImport } from './routes/apply.training-institute'
import { Route as ApplySuccessRouteImport } from './routes/apply.success'
import { Route as ApplyAuditorRouteImport } from './routes/apply.auditor'
import { Route as ApplyAdvisoryRouteImport } from './routes/apply.advisory'
import { Route as ApplyAccreditationRouteImport } from './routes/apply.accreditation'
import { Route as AdminTrainingInstitutesRouteImport } from './routes/admin.training-institutes'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCredentialsRouteImport } from './routes/admin.credentials'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminAuditorsRouteImport } from './routes/admin.auditors'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdvisoryRouteImport } from './routes/admin.advisory'
import { Route as AdminTrainingInstitutesIdRouteImport } from './routes/admin.training-institutes_.$id'
import { Route as AdminTrainingInstitutesBulkEmailCampaignsRouteImport } from './routes/admin.training-institutes.bulk-email-campaigns'
import { Route as AdminCredentialsIdRouteImport } from './routes/admin.credentials_.$id'
import { Route as AdminCredentialsPendingRouteImport } from './routes/admin.credentials.pending'
import { Route as AdminCredentialsGeneratedRouteImport } from './routes/admin.credentials.generated'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications_.$id'
import { Route as AdminAdvisoryIdRouteImport } from './routes/admin.advisory_.$id'
import { Route as AdminCredentialsGenerateApplicationIdRouteImport } from './routes/admin.credentials.generate.$applicationId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyTrainingInstituteRoute = ApplyTrainingInstituteRouteImport.update({
  id: '/training-institute',
  path: '/training-institute',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplySuccessRoute = ApplySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyAuditorRoute = ApplyAuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyAdvisoryRoute = ApplyAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyAccreditationRoute = ApplyAccreditationRouteImport.update({
  id: '/accreditation',
  path: '/accreditation',
  getParentRoute: () => ApplyRoute,
} as any)
const AdminTrainingInstitutesRoute = AdminTrainingInstitutesRouteImport.update({
  id: '/admin/training-institutes',
  path: '/admin/training-institutes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditorsRoute = AdminAuditorsRouteImport.update({
  id: '/admin/auditors',
  path: '/admin/auditors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdvisoryRoute = AdminAdvisoryRouteImport.update({
  id: '/admin/advisory',
  path: '/admin/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingInstitutesIdRoute =
  AdminTrainingInstitutesIdRouteImport.update({
    id: '/admin/training-institutes_/$id',
    path: '/admin/training-institutes/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTrainingInstitutesBulkEmailCampaignsRoute =
  AdminTrainingInstitutesBulkEmailCampaignsRouteImport.update({
    id: '/bulk-email-campaigns',
    path: '/bulk-email-campaigns',
    getParentRoute: () => AdminTrainingInstitutesRoute,
  } as any)
const AdminCredentialsIdRoute = AdminCredentialsIdRouteImport.update({
  id: '/admin/credentials_/$id',
  path: '/admin/credentials/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsPendingRoute = AdminCredentialsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminCredentialsRoute,
} as any)
const AdminCredentialsGeneratedRoute =
  AdminCredentialsGeneratedRouteImport.update({
    id: '/generated',
    path: '/generated',
    getParentRoute: () => AdminCredentialsRoute,
  } as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/admin/applications_/$id',
  path: '/admin/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdvisoryIdRoute = AdminAdvisoryIdRouteImport.update({
  id: '/admin/advisory_/$id',
  path: '/admin/advisory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsGenerateApplicationIdRoute =
  AdminCredentialsGenerateApplicationIdRouteImport.update({
    id: '/generate/$applicationId',
    path: '/generate/$applicationId',
    getParentRoute: () => AdminCredentialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/documentation': typeof DocumentationRoute
  '/governance': typeof GovernanceRoute
  '/not-found': typeof NotFoundRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/advisory': typeof AdminAdvisoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/auditors': typeof AdminAuditorsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/credentials': typeof AdminCredentialsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/training-institutes': typeof AdminTrainingInstitutesRouteWithChildren
  '/apply/accreditation': typeof ApplyAccreditationRoute
  '/apply/advisory': typeof ApplyAdvisoryRoute
  '/apply/auditor': typeof ApplyAuditorRoute
  '/apply/success': typeof ApplySuccessRoute
  '/apply/training-institute': typeof ApplyTrainingInstituteRoute
  '/admin/advisory/$id': typeof AdminAdvisoryIdRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/credentials/generated': typeof AdminCredentialsGeneratedRoute
  '/admin/credentials/pending': typeof AdminCredentialsPendingRoute
  '/admin/credentials/$id': typeof AdminCredentialsIdRoute
  '/admin/training-institutes/bulk-email-campaigns': typeof AdminTrainingInstitutesBulkEmailCampaignsRoute
  '/admin/training-institutes/$id': typeof AdminTrainingInstitutesIdRoute
  '/admin/credentials/generate/$applicationId': typeof AdminCredentialsGenerateApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/documentation': typeof DocumentationRoute
  '/governance': typeof GovernanceRoute
  '/not-found': typeof NotFoundRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/advisory': typeof AdminAdvisoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/auditors': typeof AdminAuditorsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/credentials': typeof AdminCredentialsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/training-institutes': typeof AdminTrainingInstitutesRouteWithChildren
  '/apply/accreditation': typeof ApplyAccreditationRoute
  '/apply/advisory': typeof ApplyAdvisoryRoute
  '/apply/auditor': typeof ApplyAuditorRoute
  '/apply/success': typeof ApplySuccessRoute
  '/apply/training-institute': typeof ApplyTrainingInstituteRoute
  '/admin/advisory/$id': typeof AdminAdvisoryIdRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/credentials/generated': typeof AdminCredentialsGeneratedRoute
  '/admin/credentials/pending': typeof AdminCredentialsPendingRoute
  '/admin/credentials/$id': typeof AdminCredentialsIdRoute
  '/admin/training-institutes/bulk-email-campaigns': typeof AdminTrainingInstitutesBulkEmailCampaignsRoute
  '/admin/training-institutes/$id': typeof AdminTrainingInstitutesIdRoute
  '/admin/credentials/generate/$applicationId': typeof AdminCredentialsGenerateApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/documentation': typeof DocumentationRoute
  '/governance': typeof GovernanceRoute
  '/not-found': typeof NotFoundRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/advisory': typeof AdminAdvisoryRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/auditors': typeof AdminAuditorsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/credentials': typeof AdminCredentialsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/training-institutes': typeof AdminTrainingInstitutesRouteWithChildren
  '/apply/accreditation': typeof ApplyAccreditationRoute
  '/apply/advisory': typeof ApplyAdvisoryRoute
  '/apply/auditor': typeof ApplyAuditorRoute
  '/apply/success': typeof ApplySuccessRoute
  '/apply/training-institute': typeof ApplyTrainingInstituteRoute
  '/admin/advisory_/$id': typeof AdminAdvisoryIdRoute
  '/admin/applications_/$id': typeof AdminApplicationsIdRoute
  '/admin/credentials/generated': typeof AdminCredentialsGeneratedRoute
  '/admin/credentials/pending': typeof AdminCredentialsPendingRoute
  '/admin/credentials_/$id': typeof AdminCredentialsIdRoute
  '/admin/training-institutes/bulk-email-campaigns': typeof AdminTrainingInstitutesBulkEmailCampaignsRoute
  '/admin/training-institutes_/$id': typeof AdminTrainingInstitutesIdRoute
  '/admin/credentials/generate/$applicationId': typeof AdminCredentialsGenerateApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/directory'
    | '/documentation'
    | '/governance'
    | '/not-found'
    | '/process'
    | '/services'
    | '/unauthorized'
    | '/admin/advisory'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit-logs'
    | '/admin/auditors'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/training-institutes'
    | '/apply/accreditation'
    | '/apply/advisory'
    | '/apply/auditor'
    | '/apply/success'
    | '/apply/training-institute'
    | '/admin/advisory/$id'
    | '/admin/applications/$id'
    | '/admin/credentials/generated'
    | '/admin/credentials/pending'
    | '/admin/credentials/$id'
    | '/admin/training-institutes/bulk-email-campaigns'
    | '/admin/training-institutes/$id'
    | '/admin/credentials/generate/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/directory'
    | '/documentation'
    | '/governance'
    | '/not-found'
    | '/process'
    | '/services'
    | '/unauthorized'
    | '/admin/advisory'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit-logs'
    | '/admin/auditors'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/training-institutes'
    | '/apply/accreditation'
    | '/apply/advisory'
    | '/apply/auditor'
    | '/apply/success'
    | '/apply/training-institute'
    | '/admin/advisory/$id'
    | '/admin/applications/$id'
    | '/admin/credentials/generated'
    | '/admin/credentials/pending'
    | '/admin/credentials/$id'
    | '/admin/training-institutes/bulk-email-campaigns'
    | '/admin/training-institutes/$id'
    | '/admin/credentials/generate/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/directory'
    | '/documentation'
    | '/governance'
    | '/not-found'
    | '/process'
    | '/services'
    | '/unauthorized'
    | '/admin/advisory'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit-logs'
    | '/admin/auditors'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/training-institutes'
    | '/apply/accreditation'
    | '/apply/advisory'
    | '/apply/auditor'
    | '/apply/success'
    | '/apply/training-institute'
    | '/admin/advisory_/$id'
    | '/admin/applications_/$id'
    | '/admin/credentials/generated'
    | '/admin/credentials/pending'
    | '/admin/credentials_/$id'
    | '/admin/training-institutes/bulk-email-campaigns'
    | '/admin/training-institutes_/$id'
    | '/admin/credentials/generate/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  DocumentationRoute: typeof DocumentationRoute
  GovernanceRoute: typeof GovernanceRoute
  NotFoundRoute: typeof NotFoundRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminAdvisoryRoute: typeof AdminAdvisoryRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminAuditorsRoute: typeof AdminAuditorsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCredentialsRoute: typeof AdminCredentialsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrainingInstitutesRoute: typeof AdminTrainingInstitutesRouteWithChildren
  AdminAdvisoryIdRoute: typeof AdminAdvisoryIdRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminCredentialsIdRoute: typeof AdminCredentialsIdRoute
  AdminTrainingInstitutesIdRoute: typeof AdminTrainingInstitutesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/training-institute': {
      id: '/apply/training-institute'
      path: '/training-institute'
      fullPath: '/apply/training-institute'
      preLoaderRoute: typeof ApplyTrainingInstituteRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/success': {
      id: '/apply/success'
      path: '/success'
      fullPath: '/apply/success'
      preLoaderRoute: typeof ApplySuccessRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/auditor': {
      id: '/apply/auditor'
      path: '/auditor'
      fullPath: '/apply/auditor'
      preLoaderRoute: typeof ApplyAuditorRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/advisory': {
      id: '/apply/advisory'
      path: '/advisory'
      fullPath: '/apply/advisory'
      preLoaderRoute: typeof ApplyAdvisoryRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/accreditation': {
      id: '/apply/accreditation'
      path: '/accreditation'
      fullPath: '/apply/accreditation'
      preLoaderRoute: typeof ApplyAccreditationRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/admin/training-institutes': {
      id: '/admin/training-institutes'
      path: '/admin/training-institutes'
      fullPath: '/admin/training-institutes'
      preLoaderRoute: typeof AdminTrainingInstitutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditors': {
      id: '/admin/auditors'
      path: '/admin/auditors'
      fullPath: '/admin/auditors'
      preLoaderRoute: typeof AdminAuditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/advisory': {
      id: '/admin/advisory'
      path: '/admin/advisory'
      fullPath: '/admin/advisory'
      preLoaderRoute: typeof AdminAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training-institutes_/$id': {
      id: '/admin/training-institutes_/$id'
      path: '/admin/training-institutes/$id'
      fullPath: '/admin/training-institutes/$id'
      preLoaderRoute: typeof AdminTrainingInstitutesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training-institutes/bulk-email-campaigns': {
      id: '/admin/training-institutes/bulk-email-campaigns'
      path: '/bulk-email-campaigns'
      fullPath: '/admin/training-institutes/bulk-email-campaigns'
      preLoaderRoute: typeof AdminTrainingInstitutesBulkEmailCampaignsRouteImport
      parentRoute: typeof AdminTrainingInstitutesRoute
    }
    '/admin/credentials_/$id': {
      id: '/admin/credentials_/$id'
      path: '/admin/credentials/$id'
      fullPath: '/admin/credentials/$id'
      preLoaderRoute: typeof AdminCredentialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials/pending': {
      id: '/admin/credentials/pending'
      path: '/pending'
      fullPath: '/admin/credentials/pending'
      preLoaderRoute: typeof AdminCredentialsPendingRouteImport
      parentRoute: typeof AdminCredentialsRoute
    }
    '/admin/credentials/generated': {
      id: '/admin/credentials/generated'
      path: '/generated'
      fullPath: '/admin/credentials/generated'
      preLoaderRoute: typeof AdminCredentialsGeneratedRouteImport
      parentRoute: typeof AdminCredentialsRoute
    }
    '/admin/applications_/$id': {
      id: '/admin/applications_/$id'
      path: '/admin/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/advisory_/$id': {
      id: '/admin/advisory_/$id'
      path: '/admin/advisory/$id'
      fullPath: '/admin/advisory/$id'
      preLoaderRoute: typeof AdminAdvisoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials/generate/$applicationId': {
      id: '/admin/credentials/generate/$applicationId'
      path: '/generate/$applicationId'
      fullPath: '/admin/credentials/generate/$applicationId'
      preLoaderRoute: typeof AdminCredentialsGenerateApplicationIdRouteImport
      parentRoute: typeof AdminCredentialsRoute
    }
  }
}

interface ApplyRouteChildren {
  ApplyAccreditationRoute: typeof ApplyAccreditationRoute
  ApplyAdvisoryRoute: typeof ApplyAdvisoryRoute
  ApplyAuditorRoute: typeof ApplyAuditorRoute
  ApplySuccessRoute: typeof ApplySuccessRoute
  ApplyTrainingInstituteRoute: typeof ApplyTrainingInstituteRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyAccreditationRoute: ApplyAccreditationRoute,
  ApplyAdvisoryRoute: ApplyAdvisoryRoute,
  ApplyAuditorRoute: ApplyAuditorRoute,
  ApplySuccessRoute: ApplySuccessRoute,
  ApplyTrainingInstituteRoute: ApplyTrainingInstituteRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface AdminCredentialsRouteChildren {
  AdminCredentialsGeneratedRoute: typeof AdminCredentialsGeneratedRoute
  AdminCredentialsPendingRoute: typeof AdminCredentialsPendingRoute
  AdminCredentialsGenerateApplicationIdRoute: typeof AdminCredentialsGenerateApplicationIdRoute
}

const AdminCredentialsRouteChildren: AdminCredentialsRouteChildren = {
  AdminCredentialsGeneratedRoute: AdminCredentialsGeneratedRoute,
  AdminCredentialsPendingRoute: AdminCredentialsPendingRoute,
  AdminCredentialsGenerateApplicationIdRoute:
    AdminCredentialsGenerateApplicationIdRoute,
}

const AdminCredentialsRouteWithChildren =
  AdminCredentialsRoute._addFileChildren(AdminCredentialsRouteChildren)

interface AdminTrainingInstitutesRouteChildren {
  AdminTrainingInstitutesBulkEmailCampaignsRoute: typeof AdminTrainingInstitutesBulkEmailCampaignsRoute
}

const AdminTrainingInstitutesRouteChildren: AdminTrainingInstitutesRouteChildren =
  {
    AdminTrainingInstitutesBulkEmailCampaignsRoute:
      AdminTrainingInstitutesBulkEmailCampaignsRoute,
  }

const AdminTrainingInstitutesRouteWithChildren =
  AdminTrainingInstitutesRoute._addFileChildren(
    AdminTrainingInstitutesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  DocumentationRoute: DocumentationRoute,
  GovernanceRoute: GovernanceRoute,
  NotFoundRoute: NotFoundRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminAdvisoryRoute: AdminAdvisoryRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminAuditorsRoute: AdminAuditorsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCredentialsRoute: AdminCredentialsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrainingInstitutesRoute: AdminTrainingInstitutesRouteWithChildren,
  AdminAdvisoryIdRoute: AdminAdvisoryIdRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminCredentialsIdRoute: AdminCredentialsIdRoute,
  AdminTrainingInstitutesIdRoute: AdminTrainingInstitutesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
